### ISSUE TITLE
요청사항

### ISSUE THREAD

**Issue by bigtorbsv** [laurens94/netflix-rewind-browser-extension#16]
키를 다른 키로 자유롭게 설정할수있으면 좋겟습니다.
이미 다른 기능으로 사용하고있는 중이라.  중복되서 곤란하네요.

**Comment by laurens94** [comment]
It will be possible in `v5.0.0`! Will release it soon

**Comment by laurens94** [comment]
The latest version has been released! It's now possible to modify the keys:

<img width="670" alt="image" src="https://github.com/user-attachments/assets/a409a535-a1f0-4943-8e17-d9f1b2da85d9">
