### ISSUE TITLE
add a URl of the web u want to use the tool on 

### ISSUE THREAD

**Issue by iisur** [laurens94/netflix-rewind-browser-extension#18]
i wish to add a URL section to add the web u want to use the tool on.

**Comment by laurens94** [comment]
That would be nice, however I think it would require a browser permission for all data on all urls upon installing the extension, which I find a too extensive permission for a plugin that should only work on the Netflix domain.

I made this other plugin that should work on all websites: https://github.com/laurens94/video-seeking-everywhere 
but that one hasn't been updated in a while.
