### ISSUE TITLE
Is it possible to change the keybinds?

### ISSUE THREAD

**Issue by karyzan** [laurens94/netflix-rewind-browser-extension#4]
Would it be possible to add the option to chose the key binds? And I assume we can't replace the arrow keybinds? 
Either way, much appreciated!

**Comment by laurens94** [comment]
It's on my todo list! It should actually also be possible to replace the default arrow-key functionality.

I won't have any time to work on it until June though, so it might take a while.

**Comment by itszux** [comment]
Did you manage to do that ? I tried setting the arrow keys but it won't override it
